package com.mlnx.chronic.entity;

public class TMedcine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medcine.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medcine.name
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medcine.pic
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medcine.desc
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String description;

    private String type;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medcine.id
     *
     * @return the value of t_medcine.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medcine.id
     *
     * @param id the value for t_medcine.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medcine.name
     *
     * @return the value of t_medcine.name
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medcine.name
     *
     * @param name the value for t_medcine.name
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medcine.pic
     *
     * @return the value of t_medcine.pic
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medcine.pic
     *
     * @param pic the value for t_medcine.pic
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public String toString() {
		return "TMedcine [id=" + id + ", name=" + name + ", pic=" + pic
				+ ", description=" + description + ", type=" + type + "]";
	}

}