package com.mlnx.chronic.entity;

import java.util.Date;

public class TRemind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.user_id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.type_id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.remind_time
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private Date remindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.repeat
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private Integer repeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind.remind_week
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String remindWeek;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.id
     *
     * @return the value of t_remind.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.id
     *
     * @param id the value for t_remind.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.user_id
     *
     * @return the value of t_remind.user_id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.user_id
     *
     * @param userId the value for t_remind.user_id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.type_id
     *
     * @return the value of t_remind.type_id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.type_id
     *
     * @param typeId the value for t_remind.type_id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.remind_time
     *
     * @return the value of t_remind.remind_time
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public Date getRemindTime() {
        return remindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.remind_time
     *
     * @param remindTime the value for t_remind.remind_time
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setRemindTime(Date remindTime) {
        this.remindTime = remindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.repeat
     *
     * @return the value of t_remind.repeat
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public Integer getRepeat() {
        return repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.repeat
     *
     * @param repeat the value for t_remind.repeat
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setRepeat(Integer repeat) {
        this.repeat = repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind.remind_week
     *
     * @return the value of t_remind.remind_week
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public String getRemindWeek() {
        return remindWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind.remind_week
     *
     * @param remindWeek the value for t_remind.remind_week
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setRemindWeek(String remindWeek) {
        this.remindWeek = remindWeek;
    }
}