package com.mlnx.chronic.entity;

public class TRemindType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind_type.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind_type.type_name
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind_type.state
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind_type.drugs
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String drugs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind_type.frequency
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remind_type.dosage
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    private String dosage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind_type.id
     *
     * @return the value of t_remind_type.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind_type.id
     *
     * @param id the value for t_remind_type.id
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind_type.type_name
     *
     * @return the value of t_remind_type.type_name
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind_type.type_name
     *
     * @param typeName the value for t_remind_type.type_name
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind_type.state
     *
     * @return the value of t_remind_type.state
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind_type.state
     *
     * @param state the value for t_remind_type.state
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind_type.drugs
     *
     * @return the value of t_remind_type.drugs
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public String getDrugs() {
        return drugs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind_type.drugs
     *
     * @param drugs the value for t_remind_type.drugs
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setDrugs(String drugs) {
        this.drugs = drugs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind_type.frequency
     *
     * @return the value of t_remind_type.frequency
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind_type.frequency
     *
     * @param frequency the value for t_remind_type.frequency
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remind_type.dosage
     *
     * @return the value of t_remind_type.dosage
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remind_type.dosage
     *
     * @param dosage the value for t_remind_type.dosage
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    public void setDosage(String dosage) {
        this.dosage = dosage;
    }
}