package com.mlnx.chronic.entity;

public class TUserExt {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user_ext.id
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user_ext.name
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user_ext.age
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	private Integer age;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user_ext.pic
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	private String pic;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user_ext.user_id
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	private Integer userId;

	private String sex;

	private Integer patientId;// 病人id，一个用户详细信息对应一个病人

	public TUserExt() {

	}

	public TUserExt(int patientId, int userId) {
		this.patientId = patientId;
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user_ext.id
	 * 
	 * @return the value of t_user_ext.id
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user_ext.id
	 * 
	 * @param id
	 *            the value for t_user_ext.id
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user_ext.name
	 * 
	 * @return the value of t_user_ext.name
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user_ext.name
	 * 
	 * @param name
	 *            the value for t_user_ext.name
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user_ext.age
	 * 
	 * @return the value of t_user_ext.age
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user_ext.age
	 * 
	 * @param age
	 *            the value for t_user_ext.age
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user_ext.pic
	 * 
	 * @return the value of t_user_ext.pic
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user_ext.pic
	 * 
	 * @param pic
	 *            the value for t_user_ext.pic
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user_ext.user_id
	 * 
	 * @return the value of t_user_ext.user_id
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user_ext.user_id
	 * 
	 * @param userId
	 *            the value for t_user_ext.user_id
	 * 
	 * @mbggenerated Tue Nov 03 14:01:00 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getPatientId() {
		return patientId;
	}

	public void setPatientId(Integer patientId) {
		this.patientId = patientId;
	}

	@Override
	public String toString() {
		return "TUserExt [id=" + id + ", name=" + name + ", age=" + age
				+ ", pic=" + pic + ", userId=" + userId + ", sex=" + sex
				+ ", patientId=" + patientId + "]";
	}

}