package com.mlnx.chronic.entity;

public class TVoipAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip_account.id
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip_account.voip_account
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    private String voipAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_voip_account.voip_password
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    private String voipPassword;
    
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip_account.id
     *
     * @return the value of t_voip_account.id
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip_account.id
     *
     * @param id the value for t_voip_account.id
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip_account.voip_account
     *
     * @return the value of t_voip_account.voip_account
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    public String getVoipAccount() {
        return voipAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip_account.voip_account
     *
     * @param voipAccount the value for t_voip_account.voip_account
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    public void setVoipAccount(String voipAccount) {
        this.voipAccount = voipAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_voip_account.voip_password
     *
     * @return the value of t_voip_account.voip_password
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    public String getVoipPassword() {
        return voipPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_voip_account.voip_password
     *
     * @param voipPassword the value for t_voip_account.voip_password
     *
     * @mbggenerated Thu Dec 03 15:04:25 CST 2015
     */
    public void setVoipPassword(String voipPassword) {
        this.voipPassword = voipPassword;
    }

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
    
    
}