package com.mlnx.chronic.mapper;

import java.util.List;

import com.mlnx.chronic.entity.TBloodPressureSetting;
import com.mlnx.chronic.vo.UserSetting;

public interface TBloodPressureSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(TBloodPressureSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    TBloodPressureSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<TBloodPressureSetting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(TBloodPressureSetting record);
    
	/**
	 * 根据用户id查找用户设置信息
	 * 
	 * @param id
	 * @return
	 */
	UserSetting selectSettingByPrimaryKey(Integer id);
	
	/**
	 * 查找所有用户设置信息
	 * 
	 * @param id
	 * @return
	 */
	List<UserSetting> selectAllSetting();
}