package com.mlnx.chronic.mapper;

import java.util.List;

import com.mlnx.chronic.entity.TMedcine;

public interface TMedcineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medcine
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medcine
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    int insert(TMedcine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medcine
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    TMedcine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medcine
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    List<TMedcine> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medcine
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    int updateByPrimaryKey(TMedcine record);
}