package com.mlnx.chronic.mapper;

import java.util.List;

import com.mlnx.chronic.entity.TRemindType;

public interface TRemindTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind_type
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind_type
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    int insert(TRemindType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind_type
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    TRemindType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind_type
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    List<TRemindType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind_type
     *
     * @mbggenerated Tue Dec 15 16:50:12 CST 2015
     */
    int updateByPrimaryKey(TRemindType record);
}