package com.mlnx.chronic.mapper;

import java.util.List;

import com.mlnx.chronic.entity.TReportContent;

public interface TReportContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    int insert(TReportContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    TReportContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    List<TReportContent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    int updateByPrimaryKey(TReportContent record);
}