package com.mlnx.chronic.mapper;

import java.util.List;

import com.mlnx.chronic.entity.TReport;

public interface TReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Oct 30 13:19:46 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Oct 30 13:19:46 CST 2015
     */
    int insert(TReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Oct 30 13:19:46 CST 2015
     */
    TReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Oct 30 13:19:46 CST 2015
     */
    List<TReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Oct 30 13:19:46 CST 2015
     */
    int updateByPrimaryKey(TReport record);
    
    List<TReport> selectByUserId(Integer id);
    
    /**
     * 获取用户最近一次报告
     * @param id
     * @return
     */
    TReport selectLastByUserId(Integer id);
}