package com.mlnx.chronic.mapper;

import java.util.List;

import com.mlnx.chronic.entity.TUserExt;
import com.mlnx.chronic.vo.UsrInfo;

public interface TUserExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    int insert(TUserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    TUserExt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    List<TUserExt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Tue Nov 03 14:01:00 CST 2015
     */
    int updateByPrimaryKey(TUserExt record);

    /**
     * 获取用户信息
     * @param list
     * @return
     */
	List<UsrInfo> findUserListByIds(List<Integer> list);
}