package com.mlnx.chronic.mapper;

import java.util.List;

import com.mlnx.chronic.entity.TUser;
import com.mlnx.chronic.vo.UserVo;

public interface TUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Fri Oct 30 13:19:46 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Fri Oct 30 13:19:46 CST 2015
	 */
	int insert(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Fri Oct 30 13:19:46 CST 2015
	 */
	TUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Fri Oct 30 13:19:46 CST 2015
	 */
	List<TUser> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Fri Oct 30 13:19:46 CST 2015
	 */
	int updateByPrimaryKey(TUser record);

	/**
	 * 获取用户信息和报告信息
	 * 
	 * @param id
	 * @return
	 */
	UserVo selectTReportsByPrimaryKey(Integer id);

	/**
	 * 根据用户手机号获取用户
	 * 
	 * @param phone
	 * @return
	 */
	TUser selectByPhone(String phone);

}