package com.mlnx.chronic.mapper;

import java.util.List;

import com.mlnx.chronic.entity.TVoipAccount;
import com.mlnx.chronic.vo.UsrVoipInfo;

public interface TVoipAccountMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_voip_account
	 * 
	 * @mbggenerated Thu Dec 03 15:04:25 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_voip_account
	 * 
	 * @mbggenerated Thu Dec 03 15:04:25 CST 2015
	 */
	int insert(TVoipAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_voip_account
	 * 
	 * @mbggenerated Thu Dec 03 15:04:25 CST 2015
	 */
	TVoipAccount selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_voip_account
	 * 
	 * @mbggenerated Thu Dec 03 15:04:25 CST 2015
	 */
	List<TVoipAccount> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_voip_account
	 * 
	 * @mbggenerated Thu Dec 03 15:04:25 CST 2015
	 */
	int updateByPrimaryKey(TVoipAccount record);

	/**
	 * 获取voip账号
	 * 
	 * @param list
	 * @return
	 */
	List<UsrVoipInfo> findVoipAccountList(List<Integer> list);
}